;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Ball.Eqipped.Fire",NewTagName="Ball.Equipped.Fire")
+GameplayTagRedirects=(OldTagName="Ball.Eqipped.Normal",NewTagName="Ball.Equipped.Normal")
+GameplayTagRedirects=(OldTagName="Ball.Eqipped",NewTagName="Ball.Equipped")
+GameplayTagList=(Tag="Ability.Active",DevComment="")
+GameplayTagList=(Tag="Ability.Dodge",DevComment="")
+GameplayTagList=(Tag="Ability.Throw",DevComment="")
+GameplayTagList=(Tag="Ability.Throw.Fire",DevComment="")
+GameplayTagList=(Tag="Ability.Throw.Ice",DevComment="")
+GameplayTagList=(Tag="Ability.Throw.Normal",DevComment="")
+GameplayTagList=(Tag="Ball.Equipped.Fire",DevComment="")
+GameplayTagList=(Tag="Ball.Equipped.Ice",DevComment="")
+GameplayTagList=(Tag="Ball.Equipped.Normal",DevComment="")
+GameplayTagList=(Tag="Ball.Fire",DevComment="Fire Ball")
+GameplayTagList=(Tag="Ball.Ice",DevComment="Ice Ball")
+GameplayTagList=(Tag="ball.normal",DevComment="Normal Ball")
+GameplayTagList=(Tag="Ball.Unlocked.Fire",DevComment="")
+GameplayTagList=(Tag="Ball.Unlocked.Ice",DevComment="")
+GameplayTagList=(Tag="Ball.Unlocked.Normal",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Event.Montage.ThrowBall",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="Input.NextBall",DevComment="")
+GameplayTagList=(Tag="Input.PrevBall",DevComment="")
+GameplayTagList=(Tag="Input.Throw",DevComment="")
+GameplayTagList=(Tag="State.Dodging",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")

